server:
  port: 8761
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
spring:
  profiles:
    active:
     - dev
---
spring:
  profiles: dev
  application:
    name: cowork-eureka-dev

---
spring:
  profiles: test
  application:
    name: cowork-eureka-test

---
spring:
profiles: prod
application:
  name: cowork-eureka-pro

